name: Publish kong-custom image [1.0-alpine]
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      env:
        KONG_BASE: kong:2.0.4-alpine
        PLUGINS: --server=http://luarocks.org/manifests/moesif kong-plugin-moesif 0.2.11-1
      with:
        name: graphip/kong-custom
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        buildargs: KONG_BASE,PLUGINS
