name: Publish kong-custom image [1.7-alpine]
on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      env:
        KONG_BASE: kong:2.4.0-alpine
        PLUGINS: --server=http://luarocks.org/manifests/moesif kong-plugin-moesif 1.0.1-1
      with:
        name: graphip/kong
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        buildargs: KONG_BASE,PLUGINS
        tags: "latest,1.7-alpine"
